name: example
description: simple_navigation example

version: 1.0.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  simple_navigation:
    path: ../

flutter:
  uses-material-design: true
